include $(MAKEDIR)/Makefile.base

PROJECTS := \
	mrudp \
	mrudp/receiver \
	mrudp/connection \
	mrudp/proxy \
	mrudp/sender \
	mrudp/socket \
	mrudp/imp

INCPATH := \
	$(timprepscius.libraries.cpp.include) \
	$(timprepscius.core.include) \
	$(timprepscius.standard.include)
	
SRC_PCH := mrudp/Precompile.pch
	
LIBFILE := libMrUDP.a

COPYTO := $(LIBRARIES)/project

include $(MAKEDIR)/Makefile.lib
