include $(MAKEDIR)/Makefile.base

PROJECTS := .
	
INCPATH := \
	$(timprepscius.mrudp.include) \
	$(timprepscius.core.include) \
	$(timprepscius.standard.include) \
	$(timprepscius.libraries.cpp.include)
	
LDPATH := $(timprepscius.libraries.cpp.link)

EXEFILE := mrudp-tests.exe

LIBS := \
	-lMrUDP \
	-lCore \
	-lcrypto \
	-lssl

LIBS += \
	-lboost-system \
	-lboost-thread \
	-lminizip \
	-lz


ifeq (OSX,$(SYSNAME))
	LIBS += -framework OpenCl -lc++
endif

ifeq (LINUX,$(SYSNAME))
	LIBS += -lm -lstdc++ -pthread
endif

include $(MAKEDIR)/Makefile.bin


